# fly.toml app configuration file generated for location-bot on 2024-03-29T18:40:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'location-bot'
primary_region = 'ord'
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]